  // CIM_System
    instance of CIM_System as $ServerSystem { InstanceID = "ServerSystem";
    CreationClassName = "CIM_System"; Name = "10.336.643.144";
   NameFormat = "IP"; PrimaryOwnerName = null; PrimaryOwnerContact = null;
   Roles = {}; EnabledState = 5; OtherEnabledState = null;
   RequestedState = 12; EnabledDefault = 2;  HealthState = 5;
   OperationalStatus = {2}; StatusDescriptions = {}; 
   Caption = "Computer System"; Description = "WBEM-enabled computer system";
   ElementName = "Computer System"; };
    // CIM_ObjectManager
    instance of CIM_ObjectManager as $ServerOM { InstanceID = "ServerOM";
   Name = "ACME:10.336.643.144"; ElementName = "ACME CIM Server";
   Description = "ACME CIM Server Version 1.5.2";
   SystemCreationClassName = "CIM_System"; SystemName = "10.336.643.144";
   CreationClassName = "CIM_ObjectManager"; PrimaryOwnerName = null;
   PrimaryOwnerContact = null; StartMode = "Automatic";
   Started = true; EnabledState = 5; OtherEnabledState = null;
   RequestedState = 12; EnabledDefault = 2; OperationalStatus = {2};
   StatusDescriptions = {}; Caption = null; };
    // CIM_Namespace
    instance of CIM_Namespace as $ServerNS { InstanceID = "ServerNS";
    SystemCreationClassName = "CIM_System"; SystemName = "10.336.643.144";
   ObjectManagerCreationClassName = "CIM_ObjectManager";
   ObjectManagerName = "ACME:10.336.643.144"; CreationClassName = "CIM_Namespace";
   Name = "cimv2"; ClassType = 2; ClassTypeVersion = null; 
   DescriptionOfClassType = "CIM"; Caption = null; Description = null;
   ElementName = null; };
    // CIM_ObjectManagerCommunicationMechanism
    instance of CIM_ObjectManagerCommunicationMechanism as $ServerOMComm { InstanceID = "ServerOMComm";
    CommunicationMechanism = 2; OtherCommunicationMechanismDescription = "CIM-XML";
   FunctionalProfilesSupported = {0};
   FunctionalProfileDescriptions = {"Unknown"};
   MultipleOperationsSupported = false; AuthenticationMechanismsSupported = {3};
   AuthenticationMechanismDescriptions = {"Basic"}; Version = "1.0";
   AdvertiseTypes = {3}; AdvertiseTypeDescriptions = {}; 
   SystemCreationClassName = "CIM_System"; SystemName = "10.336.643.144";
   CreationClassName = "CIM_ObjectManagerCommunicationMechanism";
   Name = "slp:https://0.0.0.0:5989"; EnabledState = 5;
   OtherEnabledState = null; RequestedState = 12; EnabledDefault = 2;
   OperationalStatus = {2}; StatusDescriptions = {"OK"}; Caption = null;
   Description = null; ElementName = "cim-xml Adapter"; };
    // CIM_CommMechanismForManager
    instance of CIM_CommMechanismForManager {
       Dependent = $ServerOMComm;
       Antecedent = $ServerOM; };
    // CIM_HostedAccessPoint
    instance of CIM_HostedAccessPoint as $HAPSS00 {
       Dependent = $ServerOMComm;
       Antecedent = $ServerSystem; };
    // CIM_HostedService
    instance of CIM_HostedService {
       Dependent = $ServerOM;
       Antecedent = $ServerSystem; };
    // CIM_NamespaceInManager
    instance of CIM_NamespaceInManager {
       Dependent = $ServerNS;
       Antecedent = $ServerOM; };
    // CIM_Registered Profile instances
    instance of CIM_RegisteredProfile as $RPSMIS {
       InstanceID = "SMI-S+1.8.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null; 
       RegisteredName = "SMI-S"; RegisteredVersion = "1.8.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S"; };

    instance of CIM_RegisteredProfile as $RPServer {
       InstanceID = "Server+1.7.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null;
       RegisteredName = "Server"; RegisteredVersion = "1.7.0";
       AdvertiseTypes = {3}; AdvertiseTypeDescriptions = {"SLP"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Server"; };
       
    instance of CIM_RegisteredProfile as $RPPRP {
       InstanceID = "Profile Registration+1.7.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null; 
       RegisteredName = "Profile Registration"; RegisteredVersion = "1.7.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Profile Registration"; };
       
    instance of CIM_RegisteredProfile as $RPIND {
       InstanceID = "Indications+1.2.2"; RegisteredOrganization = 2;
       OtherRegisteredOrganization = null; 
       RegisteredName = "Indications"; RegisteredVersion = "1.2.2";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "DMTF Indications"; };
       
    instance of CIM_RegisteredProfile as $RPNASHead {
       InstanceID = "NAS Head+1.7.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null;
       RegisteredName = "NAS Head"; RegisteredVersion = "1.7.0";
       AdvertiseTypes = {3}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S NAS Head"; };
    instance of CIM_RegisteredProfile as $RPFS {
       InstanceID = "Filesystem+1.7.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null;
       RegisteredName = "Filesystem"; RegisteredVersion = "1.7.0";
       AdvertiseTypes = {3}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Filesystem"; };
    instance of CIM_RegisteredProfile as $RPFileStorage {
       InstanceID = "File Storage+1.4.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null;
       RegisteredName = "File Storage"; RegisteredVersion = "1.4.0";
       AdvertiseTypes = {3}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S File Storage"; };
    instance of CIM_RegisteredProfile as $RPFileExport {
       InstanceID = "File Export+1.7.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null;
       RegisteredName = "File Export"; RegisteredVersion = "1.7.0";
       AdvertiseTypes = {3}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S File Export"; };
       
    instance of CIM_RegisteredProfile as $RPPP {
       InstanceID = "Physical Package+1.8.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null; 
       RegisteredName = "Physical Package"; RegisteredVersion = "1.8.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Physical Package"; };
    instance of CIM_RegisteredProfile as $RPBS {
       InstanceID = "Block Services+1.8.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null; 
       RegisteredName = "Block Services"; RegisteredVersion = "1.8.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Block Services"; };
    instance of CIM_RegisteredProfile as $RPNASNP {
       InstanceID = "NAS Network Port+1.7.0";
       RegisteredOrganization = 11; OtherRegisteredOrganization = null;
       RegisteredName = "NAS Network Port"; RegisteredVersion = "1.7.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S NAS Network Port"; };
    instance of CIM_RegisteredProfile as $RPSOFTWARE {
       InstanceID = "Software+1.8.0"; RegisteredOrganization = 11;
       OtherRegisteredOrganization = null; 
       RegisteredName = "Software"; RegisteredVersion = "1.8.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Software"; };
//    instance of CIM_RegisteredProfile as $RPDDLITE {
//       InstanceID = "Disk Drive Lite+1.8.0";
//       RegisteredOrganization = 11; OtherRegisteredOrganization = null;
//       RegisteredName = "Disk Drive Lite"; RegisteredVersion = "1.8.0";
//       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
//       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Disk Drive Lite"; };
    instance of CIM_RegisteredProfile as $RPFSPerf {
       InstanceID = "Filesystem Performance+1.8.0";
       RegisteredOrganization = 11; OtherRegisteredOrganization = null;
       RegisteredName = "Filesystem Performance"; RegisteredVersion = "1.8.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Filesystem Performance"; };
    instance of CIM_RegisteredProfile as $RPMultiCS {
       InstanceID = "Multiple Computer System+1.2.0";
       RegisteredOrganization = 11; OtherRegisteredOrganization = null;
       RegisteredName = "Multiple Computer System"; RegisteredVersion = "1.2.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"};
       Caption = "SMI-S"; Description = "SMI-S"; ElementName = "SMI-S Multiple Computer System"; };

    // A CIM_ComputerSystem instance
    instance of CIM_ComputerSystem as $CS0 { InstanceID = "CS0";
        NameFormat = "Other"; Dedicated = {24};
        CreationClassName = "CIM_ComputerSystem"; Name = "ACME+CF2A5091300089";
        OtherIdentifyingInfo = {"navinas212192"};
        IdentifyingDescriptions = {"HostName"};
        OperationalStatus = {2};
        Caption = "NAS Head";
        ElementName = "NAS Head Top level System"; };
        
    // CIM_ElementConformsToProfile instances
    instance of CIM_ElementConformsToProfile as $ECTPNASHeadSys {
       ConformantStandard = $RPNASHead;
       ManagedElement = $CS0; };
    instance of CIM_ElementConformsToProfile as $ECTPNASHeadSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPNASHead; };
    instance of CIM_ElementConformsToProfile as $ECTPFSSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPFS; };
    instance of CIM_ElementConformsToProfile as $ECTPFileStorageSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPFileStorage; };
    instance of CIM_ElementConformsToProfile as $ECTPFileExportSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPFileExport; };
    instance of CIM_ElementConformsToProfile as $ECTPRPBSSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPBS; };
    instance of CIM_ElementConformsToProfile as $ECTPRPNASNPPSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPNASNP; };
    instance of CIM_ElementConformsToProfile as $ECTPRPPPSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPPP; };
    instance of CIM_ElementConformsToProfile as $ECTPRPSOFTWARESMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPSOFTWARE; };
//    instance of CIM_ElementConformsToProfile as $ECTPRPDDLITESMIS {
//       ConformantStandard = $RPSMIS;
//       ManagedElement = $RPDDLITE; };
    instance of CIM_ElementConformsToProfile as $ECTPRPFSPerfSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPFSPerf; };
    instance of CIM_ElementConformsToProfile as $ECTPRPMultiCSSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPMultiCS; };
    instance of CIM_ElementConformsToProfile as $ECTPServerOM {
       ConformantStandard = $RPServer;
       ManagedElement = $ServerOM; };
    instance of CIM_ElementConformsToProfile as $ECTPRPServerSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPServer; };
    instance of CIM_ElementConformsToProfile as $ECTPRPPRPSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPPRP; };
    instance of CIM_ElementConformsToProfile as $ECTPRPINDSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPIND; };
    
    // CIM_ReferencedProfile instances
    instance of CIM_ReferencedProfile as $RPNASHeadPP {
       Antecedent = $RPNASHead;
       Dependent = $RPPP; };
    instance of CIM_ReferencedProfile as $RPNASHeadBS {
       Antecedent = $RPNASHead;
       Dependent = $RPBS; };
    instance of CIM_ReferencedProfile as $RPNASHeadNASNP {
       Antecedent = $RPNASHead;
       Dependent = $RPNASNP; };
    instance of CIM_ReferencedProfile as $RPNASNPIND {
       Antecedent = $RPNASNP;
       Dependent = $RPIND; };
    instance of CIM_ReferencedProfile as $RPNASHeadSOFTWARE {
       Antecedent = $RPNASHead;
       Dependent = $RPSOFTWARE; };
//    instance of CIM_ReferencedProfile as $RPArrayDDLITE {
//       Antecedent = $RPArray;
//       Dependent = $RPDDLITE; };
//    instance of CIM_ReferencedProfile as $RPDDLITEIND {
//       Antecedent = $RPDDLITE;
//       Dependent = $RPIND; };
    instance of CIM_ReferencedProfile as $RPNASHeadFSPerf {
       Antecedent = $RPNASHead;
       Dependent = $RPFSPerf; };
    instance of CIM_ReferencedProfile as $RPFSPerfNASNP {
       Antecedent = $RPFSPerf;
       Dependent = $RPNASNP; };
    instance of CIM_ReferencedProfile as $RPFSPerfFS {
       Antecedent = $RPFSPerf;
       Dependent = $RPFS; };
    instance of CIM_ReferencedProfile as $RPFSPerfFileExport {
       Antecedent = $RPFSPerf;
       Dependent = $RPFileExport; };
    instance of CIM_ReferencedProfile as $RPNASHeadMultiCS {
       Antecedent = $RPNASHead;
       Dependent = $RPMultiCS; };
    instance of CIM_ReferencedProfile as $RPServerPRP {
       Antecedent = $RPServer;
       Dependent = $RPPRP; };
    instance of CIM_ReferencedProfile as $RPServerIND {
       Antecedent = $RPServer;
       Dependent = $RPIND; };


    instance of CIM_SoftwareIdentity as $NASHeadSoftware {
      InstanceID = "ACME NAS Software+CF2A5091300089";
      IsLargeBuildNumber = false;
      VersionString = "01.6.6";
      Manufacturer = "ACME Corporation";
      IsEntity = false;
      ElementName = "ACME NASHead CF2A5091300089"; };
      
    instance of CIM_SoftwareIdentity as $ServerSoftware  {
       InstanceID = "ManagementServerSoftwareIdentity";
       MajorVersion = 4; MinorVersion = 6; RevisionNumber = 1; BuildNumber = 2;
       IsLargeBuildNumber = false;
      VersionString = "V4.6.1.2";
      Manufacturer = "SW Inc";
      Classifications = {5};
      IsEntity = false;
      Name = "SW Inc Management Server Software";
      ElementName = "SW Inc SMI-S Server Provider V4.6.1.2"; };
      
    // CIM_ElementSoftwareIdentity instances
       instance of CIM_ElementSoftwareIdentity as $ESIRPServer {
          Antecedent = $ServerSoftware;
          Dependent = $RPServer; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPPRP {
          Antecedent = $ServerSoftware;
          Dependent = $RPPRP; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPIND {
          Antecedent = $ServerSoftware;
          Dependent = $RPIND; };

       instance of CIM_ElementSoftwareIdentity as $ESIRPNASHead {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPNASHead; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPBS {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPBS; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPNASNP {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPNASNP; };
          
//       instance of CIM_ElementSoftwareIdentity as $ESIRPDDLITE {
//         Antecedent = $NASHeadSoftware;
//         Dependent = $RPDDLITE; };
         
       instance of CIM_ElementSoftwareIdentity as $ESIRPBSPerf {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPFSPerf; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPMultiCS {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPMultiCS; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPSOFTWARE {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPSOFTWARE; };
          
       instance of CIM_ElementSoftwareIdentity as $ESIRPPP {
          Antecedent = $NASHeadSoftware;
          Dependent = $RPPP; };
          
    // INDICATIONS CLASSES
    // A CIM_IndicationService instance
    instance of CIM_IndicationService as $INDSERV {
       Name = "Indication Service";
      CreationClassName = "CIM_IndicationService";
      SystemName = "10.336.643.144";
      SystemCreationClassName = "CIM_System";
      FilterCreationEnabled = true;
      DeliveryRetryAttempts = 3;
      DeliveryRetryInterval = 30;
      SubscriptionRemovalAction = 4;
      SubscriptionRemovalTimeInterval = 0; };
     
    // Instances of  CIM_FilterCollection 
    instance of CIM_FilterCollection as $INDStatFiltColl {
       InstanceID = "10.336.643.144:StaticFilterCollection";
       CollectionName = "StaticFilterCollection"; };
    instance of CIM_FilterCollection as $INDNASHeadFiltColl {
       InstanceID = "10.336.643.144:NASHeadFilterCollection";
       CollectionName = "SNIA:NAS Head:FilterCollection"; };
    instance of CIM_FilterCollection as $INDBSFiltColl {
       InstanceID = "10.336.643.144:BSFilterCollection";
       CollectionName = "SNIA:Block Services:FilterCollection"; };
//    instance of CIM_FilterCollection as $INDDDLFiltColl {
//       InstanceID = "10.336.643.144:DDLFilterCollection";
//       CollectionName = "SNIA:Disk Drive Lite:FilterCollection"; };
    instance of CIM_FilterCollection as $INDFSFiltColl {
       InstanceID = "10.336.643.144:FSFilterCollection";
       CollectionName = "SNIA:Filesystem:FilterCollection"; };
    instance of CIM_FilterCollection as $INDFileExportFiltColl {
       InstanceID = "10.336.643.144:FileExportFilterCollection";
       CollectionName = "SNIA:File Export:FilterCollection"; };
    instance of CIM_FilterCollection as $INDNASNPFiltColl {
       InstanceID = "10.336.643.144:NASNPFilterCollection";
       CollectionName = "SNIA:NAS Network Port:FilterCollection"; };
    instance of CIM_FilterCollection as $INDMCSFiltColl {
       InstanceID = "10.336.643.144:MCSFilterCollection";
       CollectionName = "SNIA:Multiple Computer System:FilterCollection"; };
    instance of CIM_FilterCollection as $INDJCFiltColl {
       InstanceID = "10.336.643.144:JobControlFilterCollection";
       CollectionName = "DMTF:Job Control:FilterCollection"; };

    // Instances of CIM_IndicationFilter
    
    instance of CIM_IndicationFilter as $INDFiltNASHead01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Logical Disk Status Change";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_LogicalDisk AND"
       "SourceInstance.CIM_LogicalDisk::OperationalStatus <> PreviousInstance.CIM_LogicalDisk::OperationalStatus";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
    
    instance of CIM_IndicationFilter as $INDFiltNASHead02 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "A LogicalDisk has degraded";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity = ‘SNIA’ AND MessageID=’DRM38’";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
       
  instance of CIM_IndicationFilter as $INDFiltNASHead03 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "A LogicalDisk has failed";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity = ‘SNIA’ AND MessageID=’DRM39’";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltNASHead04 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "A LogicalDisk has returned to normal service";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity = ‘SNIA’ AND MessageID=’DRM40’";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltBS01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Pool Creation";
       Query = "SELECT * FROM CIM_InstCreation WHERE SourceInstance ISA CIM_StoragePool";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
       
    instance of CIM_IndicationFilter as $INDFiltBS02 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Pool Deletion";
       Query = "SELECT * FROM CIM_InstDeletion WHERE SourceInstance ISA CIM_StoragePool";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltBS03 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Change in Pool TotalManagedSpace";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_StoragePool AND SourceInstance.CIM_StoragePool::TotalManagedSpace <> PreviousInstance.CIM_StoragePool::TotalManagedSpace";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltBS04 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Pool capacity is running low.";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity='SNIA' and MessageID='DRM28'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltBS05 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Pool capacity has run out";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity='SNIA' and MessageID='DRM29'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltBS06 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Pool capacity condition has been cleared";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity='SNIA' and MessageID='DRM30'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
    
    instance of CIM_IndicationFilter as $INDFiltFS01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem Creation";
       Query = "SELECT * FROM CIM_InstCreation WHERE SourceInstance ISA CIM_LocalFileSystem";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
       
    instance of CIM_IndicationFilter as $INDFiltFS02 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem Deletion";
       Query = "SELECT * FROM CIM_InstDeletion WHERE SourceInstance ISA CIM_LocalFileSystem";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFS03 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem Status Change";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_LocalFileSystem AND "
       "SourceInstance.CIM_LocalFileSystem::OperationalStatus <> PreviousInstance.CIM_LocalFileSystem::OperationalStatus";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFS04 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem capacity is at warning threshold";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity='SNIA' and MessageID='DRM28'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFS05 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem capacity is critical.";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity='SNIA' and MessageID='DRM29'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFS06 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filsystem capacity issues resolved";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity='SNIA' and MessageID='DRM30'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFS07 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem is inaccessible";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity = 'SNIA' AND MessageID='FSM14''";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFS08 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Filesystem has returned to normal access";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity = 'SNIA' AND MessageID='FSM15'";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFileExport01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Creation of a FileShare element";
       Query = "SELECT * FROM CIM_InstCreation WHERE SourceInstance ISA CIM_FileShare";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFileExport02 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Deletion of a FileShare element";
       Query = "SELECT * FROM CIM_InstDeletion WHERE SourceInstance ISA CIM_FileShare";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltFileExport03 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "FileShare issues have been cleared";
       Query = "SELECT * FROM CIM_AlertIndication WHERE OwningEntity = 'SNIA' AND MessageID='FSM17’";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltNASNP01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "NAS Network Port Status Change";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_NetworkPort AND "
       "SourceInstance.CIM_NetworkPort::OperationalStatus <> PreviousInstance.CIM_NetworkPort::OperationalStatus";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltNASNP02 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "NAS ProtocolEndpoinnt Status change";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_ProtocolEndpoint AND "
       "SourceInstance.CIM_ProtocolEndpoint::OperationalStatus <> PreviousInstance.CIM_ProtocolEndpoint::OperationalStatus";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltMCS01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Status of System Redundancy has changed";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_RedundancySet AND SourceInstance.CIM_RedundancySet::RedundancyStatus <> PreviousInstance.CIM_RedundancySet::RedundancyStatus";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };

    instance of CIM_IndicationFilter as $INDFiltJobControl01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Creation of a job";
       Query = "SELECT * FROM CIM_InstCreation WHERE SourceInstance ISA CIM_ConcreteJob";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
  instance of CIM_IndicationFilter as $INDFiltJobControl02 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Change in job State";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_ConcreteJob AND SourceInstance.CIM_ConcreteJob::JobState <> PreviousInstance.CIM_ConcreteJob::JobState";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
  instance of CIM_IndicationFilter as $INDFiltJobControl03 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Job Completed with an Exception/Error";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_ConcreteJob AND ANY SourceInstance.CIM_ConcreteJob::OperationalStatus[*] = 17 AND ANY SourceInstance.CIM_ConcreteJob::OperationalStatus[*] = 6";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
  instance of CIM_IndicationFilter as $INDFiltJobControl04 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Job Completed Successfully";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_ConcreteJob AND ANY SourceInstance.CIM_ConcreteJob::OperationalStatus[*] = 17 AND ANY SourceInstance.CIM_ConcreteJob::OperationalStatus[*] = 2";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
  instance of CIM_IndicationFilter as $INDFiltJobControl05 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IndicationFilter";
       SystemName = "10.336.643.144";
       Name = "Change in PercentComplete";
       Query = "SELECT * FROM CIM_InstModification WHERE SourceInstance ISA CIM_ConcreteJob AND SourceInstance.CIM_ConcreteJob::PercentComplete <> PreviousInstance.CIM_ConcreteJob::PercentComplete";
       QueryLanguage = "DMTF:CQL";
       SourceNamespaces = "cim/v2";
       IndividualSubscriptionSupported = true; };
       



    // A CIM_ConcreteDependency Instance
     instance of CIM_ConcreteDependency as $CDRPSFC {
        Antecedent = $RPIND;
        Dependent = $INDStatFiltColl; };
     instance of CIM_ConcreteDependency as $CDRPNASHead {
        Antecedent = $RPNASHead;
        Dependent = $INDNASHeadFiltColl; };
     instance of CIM_ConcreteDependency as $CDRPBS {
        Antecedent = $RPBS;
        Dependent = $INDBSFiltColl; };
//     instance of CIM_ConcreteDependency as $CDRPDDL {
//        Antecedent = $RPDDLite;
//        Dependent = $INDDDLFiltColl; };
     instance of CIM_ConcreteDependency as $CDRPFS {
        Antecedent = $RPFS;
        Dependent = $INDFSFiltColl; };
     instance of CIM_ConcreteDependency as $CDRPFE {
        Antecedent = $RPFileExport;
        Dependent = $INDFileExportFiltColl; };
     instance of CIM_ConcreteDependency as $CDRPNASNP {
        Antecedent = $RPNASNP;
        Dependent = $INDNASNPFiltColl; };
     instance of CIM_ConcreteDependency as $CDRPMCS {
        Antecedent = $RPMultiCS;
        Dependent = $INDMCSFiltColl; };
        
    // A CIM_ElementConformsToProfile Instance
     instance of CIM_ElementConformsToProfile as $ECTPRPINDIS {
        ManagedElement = $INDSERV;
        ConformantStandard = $RPIND; };

    // A CIM_HostedService Instance
     instance of CIM_HostedService as $HSSIS {
        Antecedent = $ServerSystem;
        Dependent = $INDSERV; };
    // Instances of CIM_OwningCollectionElement
     instance of CIM_OwningCollectionElement as $OCEISFCStatic {
        OwningElement  = $INDSERV;
        OwnedElement = $INDStatFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCNASHead {
        OwningElement  = $INDSERV;
        OwnedElement = $INDNASHeadFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCBS {
        OwningElement  = $INDSERV;
        OwnedElement = $INDBSFiltColl; };
//     instance of CIM_OwningCollectionElement as $OCEISFCDDL {
//        OwningElement  = $INDSERV;
//        OwnedElement = $INDDDLFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCFS {
        OwningElement  = $INDSERV;
        OwnedElement = $INDFSFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCFileExport {
        OwningElement  = $INDSERV;
        OwnedElement = $INDFileExportFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCNASNP {
        OwningElement  = $INDSERV;
        OwnedElement = $INDNASNPFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCMCS {
        OwningElement  = $INDSERV;
        OwnedElement = $INDMCSFiltColl; };
     instance of CIM_OwningCollectionElement as $OCEISFCJC {
        OwningElement  = $INDSERV;
        OwnedElement = $INDJCFiltColl; };
    // Instances of CIM_ServiceAffectsElement
     instance of CIM_ServiceAffectsElement as $SAEISIFNASH01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltNASHead01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFNASH02 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltNASHead02; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFNASH03 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltNASHead03; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFNASH04 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltNASHead04; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFBS01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltBS01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFBS02 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltBS02; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFBS03 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltBS03; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFBS04 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltBS04; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFBS05 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltBS05; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFBS06 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltBS06; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS02 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS02; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS03 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS03; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS04 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS04; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS05 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS05; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS06 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS06; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS07 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS07; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFS08 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFS08; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFE01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFileExport01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFE02 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFileExport02; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFFE03 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltFileExport03; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFNASNP01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltNASNP01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFNASNP02 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltNASNP02; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFMCS01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltMCS01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFJC01 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltJobControl01; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFJC02 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltJobControl02; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFJC03 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltJobControl03; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFJC04 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltJobControl04; }; 
     instance of CIM_ServiceAffectsElement as $SAEISIFJC05 {
        AffectingElement = $INDSERV;
        AffectedElement = $INDFiltJobControl05; }; 


    // Instances of CIM_MemberOfCollection
    instance of CIM_MemberOfCollection as $MOCStatNASHColl {
      Collection = $INDStatFiltColl;
      Member = $INDNASHeadFiltColl; };
     instance of CIM_MemberOfCollection as $MOCNASHFCNHIF01 {
        Collection = $INDNASHeadFiltColl;
        Member = $INDFiltNASHead01; }; 
     instance of CIM_MemberOfCollection as $MOCNASHFCNHIF02 {
        Collection = $INDNASHeadFiltColl;
        Member = $INDFiltNASHead02; }; 
     instance of CIM_MemberOfCollection as $MOCNASHFCNHIF03 {
        Collection = $INDNASHeadFiltColl;
        Member = $INDFiltNASHead03; }; 
     instance of CIM_MemberOfCollection as $MOCNASHFCNHIF04 {
        Collection = $INDNASHeadFiltColl;
        Member = $INDFiltNASHead04; }; 
    instance of CIM_MemberOfCollection as $MOCStatBSColl {
      Collection = $INDStatFiltColl;
      Member = $INDBSFiltColl; };
     instance of CIM_MemberOfCollection as $MOCBFCBIF01 {
        Collection = $INDBSFiltColl;
        Member = $INDFiltBS01; }; 
     instance of CIM_MemberOfCollection as $MOCBFCBIF02 {
        Collection = $INDBSFiltColl;
        Member = $INDFiltBS02; }; 
     instance of CIM_MemberOfCollection as $MOCBFCBIF03 {
        Collection = $INDBSFiltColl;
        Member = $INDFiltBS03; }; 
     instance of CIM_MemberOfCollection as $MOCBFCBIF04 {
        Collection = $INDBSFiltColl;
        Member = $INDFiltBS04; }; 
     instance of CIM_MemberOfCollection as $MOCBFCBIF05 {
        Collection = $INDBSFiltColl;
        Member = $INDFiltBS05; }; 
     instance of CIM_MemberOfCollection as $MOCBFCBIF06 {
        Collection = $INDBSFiltColl;
        Member = $INDFiltBS06; }; 
    instance of CIM_MemberOfCollection as $MOCStatFSColl {
      Collection = $INDStatFiltColl;
      Member = $INDFSFiltColl; };
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF01 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS01; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF02 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS02; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF03 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS03; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF04 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS04; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF05 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS05; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF06 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS06; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF07 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS07; }; 
    instance of CIM_MemberOfCollection as $MOCFSFCFSIF08 {
      Collection = $INDFSFiltColl;
      Member = $INDFiltFS08; }; 
    instance of CIM_MemberOfCollection as $MOCStatFEColl {
      Collection = $INDStatFiltColl;
      Member = $INDFileExportFiltColl; };
     instance of CIM_MemberOfCollection as $MOCFEFCFEIF01 {
        Collection = $INDFileExportFiltColl;
        Member = $INDFiltFileExport01; }; 
     instance of CIM_MemberOfCollection as $MOCFEFCFEIF02 {
        Collection = $INDFileExportFiltColl;
        Member = $INDFiltFileExport02; }; 
     instance of CIM_MemberOfCollection as $MOCFEFCFEIF03 {
        Collection = $INDFileExportFiltColl;
        Member = $INDFiltFileExport03; }; 
    instance of CIM_MemberOfCollection as $MOCStatNASNPColl {
      Collection = $INDStatFiltColl;
      Member = $INDNASNPFiltColl; };
     instance of CIM_MemberOfCollection as $MOCNASNPFCNASNPIF01 {
        Collection = $INDNASNPFiltColl;
        Member = $INDFiltNASNP01; }; 
     instance of CIM_MemberOfCollection as $MOCNASNPFCNASNPIF02 {
        Collection = $INDNASNPFiltColl;
        Member = $INDFiltNASNP02; }; 
    instance of CIM_MemberOfCollection as $MOCStatMCSColl {
      Collection = $INDStatFiltColl;
      Member = $INDMCSFiltColl; };
    instance of CIM_MemberOfCollection as $MOCMFCMIF01 {
        Collection = $INDMCSFiltColl;
        Member = $INDFiltMCS01; }; 
    instance of CIM_MemberOfCollection as $MOCStatJobControlColl {
      Collection = $INDStatFiltColl;
      Member = $INDJCFiltColl; };
     instance of CIM_MemberOfCollection as $MOCAFCAIF01 {
        Collection = $INDJCFiltColl;
        Member = $INDFiltJobControl01; }; 
     instance of CIM_MemberOfCollection as $MOCAFCAIF02 {
        Collection = $INDJCFiltColl;
        Member = $INDFiltJobControl02; }; 
     instance of CIM_MemberOfCollection as $MOCAFCAIF03 {
        Collection = $INDJCFiltColl;
        Member = $INDFiltJobControl03; }; 
     instance of CIM_MemberOfCollection as $MOCAFCAIF04 {
        Collection = $INDJCFiltColl;
        Member = $INDFiltJobControl04; }; 
     instance of CIM_MemberOfCollection as $MOCAFCAIF05 {
        Collection = $INDJCFiltColl;
        Member = $INDFiltJobControl05; }; 

// WBEM Server Classes
    // CIM_RegisteredProfile instances (WBEM Server, IP Interface, etc
    // InstanceID
    // RegisteredName,RegisteredOrganization,RegisteredVersion
    // AdvertiseTypes,ImplementedFeatures
    instance of CIM_RegisteredProfile as $RPWBEMServer {
      InstanceID = "WBEM Server 1.0.1i";
      RegisteredName = "WBEM Server";
      RegisteredOrganization = 2;
      RegisteredVersion = "1.0.1i";
      AdvertiseTypes = {3};
      AdvertiseTypeDescriptions = {"SLP"};
      ImplementedFeatures = {""}; }; 
    instance of CIM_RegisteredProfile as $RPDMTFPRP {
       InstanceID = "DMTF Profile Registration+1.0"; RegisteredOrganization = 2;
       OtherRegisteredOrganization = null; 
       RegisteredName = "Profile Registration"; RegisteredVersion = "1.0";
       AdvertiseTypes = {2}; AdvertiseTypeDescriptions = {"Not Advertised"}; };
    instance of CIM_RegisteredProfile as $RPIPInterface {
      InstanceID = "IP Interface 1.1.1";
      RegisteredName = "IP Interface";
      RegisteredOrganization = 2;
      RegisteredVersion = "1.1.1";
      AdvertiseTypes = {};
      AdvertiseTypeDescriptions = {}; }; 
    instance of CIM_RegisteredProfile as $RPJobControl {
      InstanceID = "Job Control 1.0.0";
      RegisteredName = "Job Control";
      RegisteredOrganization = 2;
      RegisteredVersion = "1.0.0";
      AdvertiseTypes = {};
      AdvertiseTypeDescriptions = {}; }; 
    instance of CIM_RegisteredProfile as $RPRoleBased {
      InstanceID = "Role Based Authorization 1.0.0";
      RegisteredName = "Role Based Authorization";
      RegisteredOrganization = 2;
      RegisteredVersion = "1.0.0";
      AdvertiseTypes = {};
      AdvertiseTypeDescriptions = {}; }; 
    instance of CIM_RegisteredProfile as $RPSimpleIdent {
      InstanceID = "Simple Identity Management 1.1.0";
      RegisteredName = "Simple Identity Management";
      RegisteredOrganization = 2;
      RegisteredVersion = "1.1.0";
      AdvertiseTypes = {};
      AdvertiseTypeDescriptions = {}; }; 
    // SHRUB: CIM_ElementConformsToProfile TO CIM_ComputerSystem
    instance of CIM_ElementConformsToProfile as $ECTPWBEMServer {
        ManagedElement = $ServerSystem;
        ConformantStandard = $RPWBEMServer; };
    // SHRUB: CIM_ElementConformsToProfile TO SMI-S RegisteredProfile
    instance of CIM_ElementConformsToProfile as $ECTPWBEMServerSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPWBEMServer; };
    instance of CIM_ElementConformsToProfile as $ECTPDMTFPRPSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPDMTFPRP; };
    instance of CIM_ElementConformsToProfile as $ECTPIPInterfaceSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPIPInterface; };
    instance of CIM_ElementConformsToProfile as $ECTPJobControlSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPJobControl; };
    instance of CIM_ElementConformsToProfile as $ECTPRoleBasedSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPRoleBased; };
    instance of CIM_ElementConformsToProfile as $ECTPSimpleIdentSMIS {
       ConformantStandard = $RPSMIS;
       ManagedElement = $RPSimpleIdent; };
    // PRP SHRUBs: CIM_ConcreteDependency to profile filter collection
     instance of CIM_ConcreteDependency as $CDRPJC {
        Antecedent = $RPJobControl;
        Dependent = $INDJCFiltColl; };
    // PRP SHRUBs: CIM_ReferencedProfile to related profiles
    instance of CIM_ReferencedProfile as $RPWBEMServerDMTFPRP {
       Antecedent = $RPWBEMServer;
       Dependent = $RPDMTFPRP; };
    instance of CIM_ReferencedProfile as $RPWBEMServerIPInterface {
       Antecedent = $RPWBEMServer;
       Dependent = $RPIPInterface; };
    instance of CIM_ReferencedProfile as $RPIPInterfaceDMTFPRP {
       Antecedent = $RPIPInterface;
       Dependent = $RPDMTFPRP; };
    instance of CIM_ReferencedProfile as $RPWBEMServerJob {
       Antecedent = $RPWBEMServer;
       Dependent = $RPJobControl; };
    instance of CIM_ReferencedProfile as $RPJobControlDMTFPRP {
       Antecedent = $RPJobControl;
       Dependent = $RPDMTFPRP; };
    instance of CIM_ReferencedProfile as $RPWBEMServerRoleBased {
       Antecedent = $RPWBEMServer;
       Dependent = $RPRoleBased; };
    instance of CIM_ReferencedProfile as $RPRoleBasedSimple {
       Antecedent = $RPRoleBased;
       Dependent = $RPSimpleIdent; };
    instance of CIM_ReferencedProfile as $RPRoleBasedDMTFPRP {
       Antecedent = $RPRoleBased;
       Dependent = $RPDMTFPRP; };
    instance of CIM_ReferencedProfile as $RPWBEMServerSimple {
       Antecedent = $RPWBEMServer;
       Dependent = $RPSimpleIdent; };
    instance of CIM_ReferencedProfile as $RPSimpleIdentDMTFPRP {
       Antecedent = $RPSimpleIdent;
       Dependent = $RPDMTFPRP; };
    instance of CIM_ReferencedProfile as $RPWBEMServerIND {
       Antecedent = $RPWBEMServer;
       Dependent = $RPIND; };
    instance of CIM_ReferencedProfile as $RPINDDMTFPRP {
       Antecedent = $RPIND;
       Dependent = $RPDMTFPRP; };
    // PRP SHRUBs: CIM_RegisteredProfile to SoftwareIdentity
       instance of CIM_ElementSoftwareIdentity as $ESIRPWBEMServ {
          Antecedent = $ServerSoftware;
          Dependent = $RPWBEMServer; };
       instance of CIM_ElementSoftwareIdentity as $ESIRPDMTFPRP {
          Antecedent = $ServerSoftware;
          Dependent = $RPDMTFPRP; };
       instance of CIM_ElementSoftwareIdentity as $ESIRPIPInterface {
          Antecedent = $ServerSoftware;
          Dependent = $RPIPInterface; };
       instance of CIM_ElementSoftwareIdentity as $ESIRPJobControl {
          Antecedent = $ServerSoftware;
          Dependent = $RPJobControl; };
       instance of CIM_ElementSoftwareIdentity as $ESIRPRoleBased {
          Antecedent = $ServerSoftware;
          Dependent = $RPRoleBased; };
       instance of CIM_ElementSoftwareIdentity as $ESIRPSimple {
          Antecedent = $ServerSoftware;
          Dependent = $RPSimpleIdent; };
    
    // CIM_CIMXMLCapabilities instances
    // InstanceID
    // AuthenticationMechanismsSupported,ElementName,GenericOperationCapabilities
    // MaxConnections,MultipleOperationsSupported,RequestedStatesSupported
    // Validated,WBEMProtocolVersionsSupported
       instance of CIM_CIMXMLCapabilities as $CIMXMLCap {
         InstanceID = "CIMXMLCapabilities Instance";
         AuthenticationMechanismsSupported = {0};
         ElementName = "WBEM Server CIMXMLCapabilities";
         ListeningPortManagementSupported = true;
         GenericOperationCapabilities = "instance of CIM_GenericOperationCapabilitiesStructure {FQLSupported = false; "
         "CQLSupport = {0}; OperationsSupported = {2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,"
         "26,27,28,29,30,31,32,33,34,35,36,37,38,39,40}; };"; 
         MaxConnections = 1;
         MultipleOperationsSupported = false;
         RequestedStatesSupported = {2,3,11};
         Validated = false;
         WBEMProtocolVersionsSupported = {"2.0.0"}; };
    // SHRUB: CIM_ElementCapabilities TO CIM_ProtocolService (see CIM_ProtocolService)
    
    // CIM_ComputerSystem instances
    // CreationClassName,Name,NameFormat
    // ElementName,EnabledState,HealthState,RequestedState
    // OperationalStatus, 
    // SHRUB: CIM_ElementConformsToProfile TO CIM_RegisteredProfile (WBEM Server) (see above)
    // CIM_HostedAccessPoint to CIM_TCPProtocolEndpoint and 
    // CIM_HostedService to CIM_WBEMServer, CIM_ProtocolService, CIM_RoleBasedAuthorizationService and CIM_AccountManagementService
    // CIM_OwningCollectionElement to CIM_Role
    // CIM_AccountOnSystem to CIM_Account
    
    // CIM_GenericOperationCapabilitiesStructure instances
    // CQLSupport,FQLSupported,OperationsSupported,
    
    // CIM_ProtocolService instances
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // ElementName,EnabledState,MaxConnections,Protocol,RequestedState
    // OperationalStatus,HealthState
    instance of CIM_ProtocolService as $PROTOSERVICE {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_ProtocolService";
       SystemName = "10.336.643.144";
       Name = "CIMXML Protocol Service";
       ElementName = "WBEM Protocol Service";
       EnabledState = 5;
       MaxConnections = 1;
       RequestedState = 12;
       OperationalStatus = {2};
       HealthState = 5; };
    // SHRUB: CIM_ElementCapabilities TO CIM_WBEMProtocolServiceCapabilities
     instance of CIM_ElementCapabilities as $ECCSP0 {
        Capabilities = $CIMXMLCap;
        ManagedElement = $PROTOSERVICE; };
    // CIM_HostedService TO CIM_ComputerSystem
       Instance of CIM_HostedService as $HSServerSysProtoService {
         Antecedent = $ServerSystem;
         Dependent = $PROTOSERVICE; };
    // CIM_ServiceAccessBySAP TO CIM_ServiceAccessPoint (see below)
    // CIM_ServiceServiceDependency TO CIM_WBEMServer (see below)
    
    // CIM_SchemaInformationStructure instance
    // Name,OwningOrganization,Version

    // CIM_TCPProtocolEndpoint instances
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // ElementName,NameFormat,PortNumber,ProtocolIFType
    instance of CIM_TCPProtocolEndpoint as $TCPPE11 {
       InstanceID = "TCPPE11";
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_TCPProtocolEndpoint";
       SystemName = "10.336.643.144";
       Name = "10.336.643.144+TCP11";
       ElementName = "WBEM Server TCP Protocol Endpoint";
       NameFormat = "<PortAddress>+<Protocol><Number>";
       OperationalStatus = {2};
       PortNumber = 11;
       ProtocolIFType = 4111; };
    // SHRUB: CIM_ServiceAccessBySAP TO CIM_ProtocolService
       instance of CIM_ServiceAccessBySAP as $SABSPSTCPPE {
          Antecedent = $PROTOSERVICE;
          Dependent = $TCPPE11; };
    // CIM_HostedAccessPoint TO CIM_ComputerSystem
      instance of CIM_HostedAccessPoint as $HAPTCPPECS11 {
        Antecedent = $ServerSystem;
        Dependent = $TCPPE11; };

    // CIM_WBEMProtocolServiceCapabilities instance (See CIMXMLCapabilities)
    // InstanceID
    // AuthenticationMechanismsSupported,GenericOperationCapabilities
    // ListeningPortManagementSupported,MaxConnections
    // RequestedStatesSupported,WBEMProtocolVersionsSupported,ElementName
    // SHRUB: CIM_ElementCapabilities TO CIM_ProtocolService

    // CIM_WBEMServer instance
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // ElementName,EnabledState,RequestedState
    // OperationalStatus,HealthState
      instance of CIM_WBEMServer as $WBEMServer {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_WBEMServer";
       SystemName = "10.336.643.144";
       Name = "WBEM Server Instance";
       ElementName = "The WBEM Server Service";
       EnabledState = 5;
       RequestedState = 12;
       OperationalStatus = {2};
       HealthState = 5; };
    // SHRUB: CIM_ElementCapabilities TO CIM_WBEMServerCapabilities (see below)
    // CIM_HostedDependency TO CIM_WBEMServerNamespace (See below)
    // CIM_HostedService TO CIM_ComputerSystem
     instance of CIM_HostedService as $HSWBEMServerServerSystem {
       Dependent = $WBEMServer;
       Antecedent = $ServerSystem; };
    // CIM_ServiceServiceDependency TO CIM_ProtocolService
      instance of CIM_ServiceServiceDependency as $SSDWSPS {
        Antecedent = $WBEMServer;
        Dependent = $PROTOSERVICE;
        TypeOfDependency = 3;
        RestartService = false; };

    // CIM_WBEMServerCapabilities INSTANCE
    // InstanceID
    // OperationsSupported,RequestedStatesSupported
      instance of CIM_WBEMServerCapabilities as $WBEMServCap {
        InstanceID = "WBEM Server Capabilities";
        OperationsSupported = {2,3,4};
        RequestedStatesSupported =  {2,3}; };
    // SHRUB: CIM_ElementCapabilities TO CIM_WBEMServer
     instance of CIM_ElementCapabilities as $ECWSCS {
        Capabilities = $WBEMServCap;
        ManagedElement = $WBEMServer; };

    // CIM_WBEMServerNamespace INSTANCES
    // InstanceID
    // Name,ElementName,SchemaInformation
      instance of CIM_WBEMServerNamespace as $WBEMServName00 {
        InstanceID = "WBEM Server Namespace 00";
        Name = "cimv2";
        ElementName = "cimv2";
        SchemaInformation = "instance of CIM_SchemaInformationStructure { Name = \"CIM\"; Version = \"2.51.0\";"
        " OwningOrganization = \"DMTF\"; Status = 3; };"; 
         };
    // SHRUB: CIM_HostedDependency TO CIM_WBEMServer
      instance of CIM_HostedDependency as $HDWSWSName00 {
        Antecedent = $WBEMServer;
        Dependent = $WBEMServName00; };
        
    // CIM_IPProtocolEndpoint instances
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // NameFormat,ProtocolIFType,RequestedState,EnabledState
    // ElementName,AddressOrigin
    // IPv4Address,SubnetMask
    // IPv6Address,IPv6SubnetPrefixLength
      instance of CIM_IPProtocolEndpoint as $IPPE11 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_IPProtocolEndpoint";
       SystemName = "10.336.643.144";
       Name = "10.336.643.144+IP11";
       ElementName = "WBEM Server IP Protocol Endpoint";
       NameFormat = "<PortAddress>+<Protocol><Number>";
       RequestedState = 2;
       EnabledState = 2;
       AddressOrigin = 3;
       IPv4Address = "0.0.0.0";
       SubnetMask = "0.0.0.0";
       ProtocolIFType = 4096; };
    // SHRUB: CIM_HostedAccessPoint TO CIM_ComputerSystem
      instance of CIM_HostedAccessPoint as $HAPIPPECS11 {
        Antecedent = $ServerSystem;
        Dependent = $IPPE11; };

    // CIM_RoleBasedManagementCapabilities instance
    // InstanceID
    // SharedPrivilegeSupported,SupportedMethods,ElementName
      instance of CIM_RoleBasedManagementCapabilities as $RBMCap {
        InstanceID = "RBMCap";
        SharedPrivilegeSupported = false; 
        SupportedMethods = {0,1,2,3,4,5,6,7,8,9};
        ElementName = "Role based management capabilities"; };
    // SHRUB: CIM_ElementCapabilities to CIM_RoleBasedAuthorizationService (see below)
 
    // CIM_Role instances
    // CreationClassName,Name
    // RoleCharacteristics,CommonName,ElementName
      instance of CIM_Role as $Role00 {
       CreationClassName = "CIM_Role";
       Name = "Admin";
       RoleCharacteristics = {2};
       CommonName = "Administrator";
       ElementName = "Storage Administrator"; };
      instance of CIM_Role as $Role01 {
       CreationClassName = "CIM_Role";
       Name = "User";
       RoleCharacteristics = {2};
       CommonName = "User";
       ElementName = "Storage User"; };
    // SHRUB: CIM_ConcreteDependency TO CIM_Identity (See below)
    // CIM_MemberOfCollection TO CIM_Privilege (N/A) AND CIM_Identity  (See below)
    // CIM_OwningCollectionElement TO CIM_ComputerSystem
      instance of CIM_OwningCollectionElement as $OCECSR00 {
        OwningElement = $ServerSystem;
        OwnedElement = $Role00; };
      instance of CIM_OwningCollectionElement as $OCECSR00 {
        OwningElement = $ServerSystem;
        OwnedElement = $Role01; };
    // CIM_RoleLimitedToTarget TO CIM_ManagedElement
      instance of CIM_RoleLimitedToTarget as $RLTTServer {
        DefiningRole = $Role00;
        TargetElement = $ServerSystem; };
      instance of CIM_RoleLimitedToTarget as $RLTTServer {
        DefiningRole = $Role00;
        TargetElement = $CS0; };
      instance of CIM_RoleLimitedToTarget as $RLTTServer {
        DefiningRole = $Role01;
        TargetElement = $ServerSystem; };
      instance of CIM_RoleLimitedToTarget as $RLTTServer {
        DefiningRole = $Role01;
        TargetElement = $CS0; };
    // CIM_ServiceAffectsElement TO CIM_RoleBasedAuthorizationService (See below)

    // CIM_RoleBasedAuthorizationService INSTANCE
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // ElementName
      instance of CIM_RoleBasedAuthorizationService as $RBAService {
       SystemCreationClassName = "CIM_System";
       SystemName = "10.336.643.144";
       CreationClassName = "CIM_RoleBasedAuthorizationService";
       Name = "RBA Service";
       ElementName = "Role Based Authorization Service"; };
    // SHRUB: CIM_ElementCapabilities TO CIM_RoleBasedManagementCapabilities
      instance of CIM_ElementCapabilities as $ECRBSRBMC {
        Capabilities = $RBMCap;
        ManagedElement = $RBAService; };
    // CIM_HostedService TO CIM_ComputerSystem
      instance of CIM_HostedService as $HSCSRBAService {
       Dependent = $RBAService;
       Antecedent = $ServerSystem; };
    // CIM_ServiceAffectsElement TO CIM_Role AND CIM_Privilege
     instance of CIM_ServiceAffectsElement as $SAERBASRole00 {
        AffectingElement = $RBAService;
        AffectedElement = $Role00; };
     instance of CIM_ServiceAffectsElement as $SAERBASRole01 {
        AffectingElement = $RBAService;
        AffectedElement = $Role01; };
    // CIM_ServiceServiceDependency TO CIM_AccountManagementService (N/A)
    
    // CIM_Account INSTANCES
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // UserID,UserPassword,OrganizationName,ElementName
    // RequestedState,EnabledState
      instance of CIM_Account as $Account00 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_Account";
       SystemName = "10.336.643.144";
       Name = "10.336.643.144+00";
       UserID = "Jane";
       UserPassword = "0o173";
       OrganizationName = "Client Lib";
       ElementName = "Jane Doe Account";
       RequestedState = 2;
       EnabledState = 2; };
      instance of CIM_Account as $Account01 {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_Account";
       SystemName = "10.336.643.144";
       Name = "10.336.643.144+01";
       UserID = "John";
       UserPassword = "0o710";
       OrganizationName = "Storage Systems";
       ElementName = "John Doe Account";
       RequestedState = 2;
       EnabledState = 2; };
    // SHRUB: CIM_AccountOnSystem TO CIM_ComputerSystem
      instance of CIM_AccountOnSystem as $AoSServerA00 {
        GroupComponent = $ServerSystem;
        PartComponent = $Account00; };
      instance of CIM_AccountOnSystem as $AoSServerA01 {
        GroupComponent = $ServerSystem;
        PartComponent = $Account01; };
    // CIM_AssignedIdentity TO CIM_Identity (See below)
    
    // CIM_AccountManagementCapabilities INSTANCE
    // InstanceID
    // ElementNameEditSupported,ElementName,OperationsSupported
      instance of CIM_AccountManagementCapabilities as $AccountCap {
        InstanceID = "Account Management Capabilities";
        ElementName = "Capabilities for Account Management Service";
        ElementNameEditSupported = false;
        OperationsSupported = {}; };
    // SHRUB: CIM_ElementCapabilities TO CIM_AccountManagementService (See Below)
    
    // CIM_AccountManagementService INSTANCE
    // SystemCreationClassName,SystemName,CreationClassName,Name
    // RequestedState,EnabledState,ElementName
      instance of CIM_AccountManagementService as $AccountService {
       SystemCreationClassName = "CIM_System";
       CreationClassName = "CIM_AccountManagementService";
       SystemName = "10.336.643.144";
       Name = "Account Management Service";
       ElementName = "Server Account Management Service";
       EnabledState = 5;
       RequestedState = 12; };
    // SHRUB: CIM_ElementCapabilities TO CIM_AccountManagementCapabilities 
      instance of CIM_ElementCapabilities as $ECAMSAMC {
        ManagedElement = $AccountService;
        Capabilities = $AccountCap; };
    // CIM_ServiceServiceDependency TO CIM_RoleBasedAuthorizationService (N/A)
    // CIM_HostedService TO CIM_ComputerSystem
      instance of CIM_HostedService as $HSAMSServer {
        Antecedent = $ServerSystem;
        Dependent = $AccountService; };
    // CIM_ServiceAffectsElement TO CIM_Identity (See below)
     /////////////////////////  
    // CIM_Identity INSTANCES
    // InstanceID
    // ElementName
      instance of CIM_Identity as $Ident00 {
        InstanceID = "Ident00";
        ElementName = "Jane Doe"; };
      instance of CIM_Identity as $Ident01 {
        InstanceID = "Ident01";
        ElementName = "John Doe"; };
    // SHRUB: CIM_ConcreteDependency TO CIM_Role
      instance of CIM_ConcreteDependency as $CDIdentRole00 {
        Antecedent = $Ident00;
        Dependent = $Role00; };
      instance of CIM_ConcreteDependency as $CDIdentRole01 {
        Antecedent = $Ident01;
        Dependent = $Role01; };
    // CIM_AssignedIdentity TO CIM_Account
      instance of CIM_AssignedIdentity as $AIAccountIdent00 {
        IdentityInfo = $Ident00;
        ManagedElement = $Account00; };
      instance of CIM_AssignedIdentity as $AIAccountIdent01 {
        IdentityInfo = $Ident01;
        ManagedElement = $Account01; };
    // CIM_ServiceAffectsElement TO CIM_AccountManagementService
      instance of CIM_ServiceAffectsElement as $SAEIdentAMS00 {
        AffectedElement = $Ident00;
        AffectingElement = $AccountService;
        ElementEffects = 5; };
      instance of CIM_ServiceAffectsElement as $SAEIdentAMS01 {
        AffectedElement = $Ident01;
        AffectingElement = $AccountService;
        ElementEffects = 5; };
       

    // NAS Head Profile classes
    // See $CS0 above

    // Multiple Computer System Profile classes
    // CIM_ComputerSystem instances
    instance of CIM_ComputerSystem as $CS_A { InstanceID = "CS_A";
       NameFormat = "Other"; Dedicated = {0};
       CreationClassName = "CIM_ComputerSystem"; Name = "ACME+CF2A5091300089+SP_A";
       OperationalStatus = {2}; 
       Caption = "Adapter SP_A present in ACME CF2A5091300089 NAS";
       ElementName = "SP_A"; };
       
    instance of CIM_ComputerSystem as $CS_B { InstanceID = "CS_B";
       NameFormat = "Other"; Dedicated = {0};
       CreationClassName = "CIM_ComputerSystem"; Name = "ACME+CF2A5091300089+SP_B";
       OperationalStatus = {2}; 
       Caption = "Adapter SP_B present in ACME CF2A5091300089 NAS";
       ElementName = "SP_B"; };
       
    instance of CIM_ComputerSystem as $CS_CIFS0 { InstanceID = "CS_CIFS0";
       NameFormat = "Other"; Dedicated = {16};
       CreationClassName = "CIM_ComputerSystem"; Name = "ACME+CF2A5091300089+SP_A+CIFS0";
       OperationalStatus = {2}; 
       Caption = "File Server SP_A CIFS Server";
       ElementName = "SP_A CIFS Server"; };
       
    instance of CIM_ComputerSystem as $CS_NFS0 { InstanceID = "CS_NFS0";
       NameFormat = "Other"; Dedicated = {16};
       CreationClassName = "CIM_ComputerSystem"; Name = "ACME+CF2A5091300089+SP_A+NFS0";
       OperationalStatus = {2}; 
       Caption = "File Server SP_A NFS Server";
       ElementName = "SP_A NFS Server"; };
       
    instance of CIM_ComputerSystem as $CS_NFS1 { InstanceID = "CS_NFS1";
       NameFormat = "Other"; Dedicated = {16};
       CreationClassName = "CIM_ComputerSystem"; Name = "ACME+CF2A5091300089+SP_B+NFS1";
       OperationalStatus = {2}; 
       Caption = "File Server SP_B NFS Server";
       ElementName = "SP_B NFS Server"; };

    // A CIM_RedundancySet instance
    instance of CIM_RedundancySet as $CSRS { InstanceID = "CSRS";
       RedundancyStatus = 2; TypeOfSet = {5};
       ElementName = "ACME_NAS_RedundancySet"; };
    
    // CIM_ComponentCS Instances
    instance of CIM_ComponentCS as $CCS_A {
     GroupComponent = $CS0;
     PartComponent = $CS_A; };
     
    instance of CIM_ComponentCS as $CCS_B {
     GroupComponent = $CS0;
     PartComponent = $CS_B; };

    // CIM_ConcreteIdentity Instance
    instance of CIM_ConcreteIdentity as $CICSRS {
      SameElement = $CSRS;
      SystemElement = $CS0; };

    
    // CIM_MemberOfCollection Instances
    instance of CIM_MemberOfCollection as $CSMOC_A {
      Collection = $CSRS;
      Member = $CS_A; };

    instance of CIM_MemberOfCollection as $CSMOC_B {
      Collection = $CSRS;
      Member = $CS_B; };
 
    // Physical Package Profile 
    // A CIM_Rack instance
     instance of CIM_Rack as $PP0 { InstanceID = "PP0";
        Caption = "CR:CF2A5091300089";
        Tag = "ACME+CF2A5091300089";
        CreationClassName = "CIM_Rack"; 
        Manufacturer = "ACME Corporation"; Model = "ACME NAS 101";
         };
     instance of CIM_Chassis as $PP0A { InstanceID = "PP0A";
        Caption = "CSPC:SP A";
        Tag = "ACME+SP A";
        CreationClassName = "CIM_Chassis"; 
        Manufacturer = "ACME Corporation"; Model = "ACME 2.13GHZ CPU";
         };
     instance of CIM_Chassis as $PP0B{ InstanceID = "PP0B";
        Caption = "CSPC:SP B";
        Tag = "ACME+SP B";
        CreationClassName = "CIM_Chassis"; 
        Manufacturer = "ACME Corporation"; Model = "ACME 2.13GHZ CPU";
         };

    // A CIM_Product instance 
     instance of CIM_Product as $P0 { InstanceID = "P0";
        Name = "ACME:CF2A5091300089"; IdentifyingNumber = "ACME+CF2A5091300089";
        Caption = "system:CF2A5091300089";
        Vendor = "ACME Corporation"; Version = "8.0.1";
        ElementName = "ACME+CF2A5091300089+ACME NAS 101"; };
        
     instance of CIM_Product as $P_A { InstanceID = "P_A";
        Name = "SP A"; IdentifyingNumber = "ACME+CF2A5091300089+SP A";
        Caption = "system:CF2A5091300089:SP A";
        Vendor = "ACME Corporation"; Version = "8.0.1";
        ElementName = "ACME+CF2A5091300089+ACME NAS Processor A"; };
        
     instance of CIM_Product as $P_B { InstanceID = "P_B";
        Name = "SP B"; IdentifyingNumber = "ACME+CF2A5091300089+SP B";
        Caption = "system:CF2A5091300089:SP B";
        Vendor = "ACME Corporation"; Version = "8.0.1";
        ElementName = "ACME+CF2A5091300089+ACME NAS Processor B"; };

    // A CIM_ProductPhysicalComponent instance      
     instance of CIM_ProductPhysicalComponent as $PPC0 {
        PartComponent = $PP0;
        GroupComponent = $P0; };
     instance of CIM_ProductPhysicalComponent as $PPCA {
        PartComponent = $PP0A;
        GroupComponent = $P_A; };
     instance of CIM_ProductPhysicalComponent as $PPCB {
        PartComponent = $PP0B;
        GroupComponent = $P_B; };
     
    // A CIM_SystemPackaging instance
     instance of CIM_SystemPackaging as $SP0 {
        Antecedent = $PP0;
        Dependent = $CS0; };
     instance of CIM_SystemPackaging as $SP0A {
        Antecedent = $PP0A;
        Dependent = $CS_A; };
     instance of CIM_SystemPackaging as $SP0B {
        Antecedent = $PP0B;
        Dependent = $CS_B; };

    // Block Services Package
    // A CIM_StoragePool (Concrete) instance
     instance of CIM_StoragePool as $CSP0 {
        InstanceID = "ACME+CF2A5091300089+C+0000"; PoolID = "0000";
        Primordial = false; TotalManagedSpace = 766413985109;
        RemainingManagedSpace = 95289906517; 
        Usage = 2; 
        OperationalStatus = {2}; 
        Caption = "NPSP:Pool0";
        ElementName = "Concrete storage pool 0000 for CF2A5091300089 NAS"; };
     instance of CIM_StoragePool as $CSP1 {
        InstanceID = "ACME+CF2A5091300089+C+0001"; PoolID = "0001";
        Primordial = false; TotalManagedSpace = 191125345621;
        RemainingManagedSpace = 190950582955; 
        Usage = 2; 
        OperationalStatus = {2}; 
        Caption = "NPSP:Pool1";
        ElementName = "Concrete storage pool 0001 for CF2A5091300089 NAS"; };

    // A CIM_StoragePool (Primordial) instance
     instance of CIM_StoragePool as $PSP0 {
        InstanceID = "ACME+CF2A5091300089+Primordial"; PoolID = "Primordial";
        Primordial = true; TotalManagedSpace = 6244252603733;
        RemainingManagedSpace = 1160305722027; 
        Usage = 2; 
        OperationalStatus = {2};
        Caption = "PSP:PSP1";
        ElementName = "Primordial storage pool for CF2A5091300089 NAS"; };

    // A CIM_AllocatedFromStoragePool instance
    instance of CIM_AllocatedFromStoragePool as $AFSP0 {
       SpaceConsumed = 948437306573; SpaceLimit = 0;
       Antecedent = $PSP0;
       Dependent = $CSP0; };
     instance of CIM_AllocatedFromStoragePool as $AFSP1 {
        SpaceConsumed = 378428184330; SpaceLimit = 0;
        Antecedent = $PSP0;
        Dependent = $CSP1; };

    // A CIM_HostedStoragePool instance
     instance of CIM_HostedStoragePool as $HSP0 {
        GroupComponent = $CS0;
        PartComponent = $CSP0; };
     instance of CIM_HostedStoragePool as $HSP1 {
        GroupComponent = $CS0;
        PartComponent = $CSP1; };
     instance of CIM_HostedStoragePool as $HSP3 {
        GroupComponent = $CS0;
        PartComponent = $PSP0; };
 
    // A CIM_StorageCapabilities instance
     instance of CIM_StorageCapabilities as $StPC0 {
        InstanceID = "ACME+CF2A5091300089+C+0000";
        ElementType = 5; NoSinglePointOfFailure = false;
        NoSinglePointOfFailureDefault = false;
        DataRedundancyMax = 1; DataRedundancyMin = 1; DataRedundancyDefault = 1;
        PackageRedundancyMax = 1; PackageRedundancyMin = 1; PackageRedundancyDefault = 1;
        ParityLayoutDefault = 2; Caption = "SPSC:Pool0";
        ElementName = "Capabilities for storage pool on CF2A5091300089 NAS"; };
     instance of CIM_StorageCapabilities as $StPC1 {
        InstanceID = "ACME+CF2A5091300089+C+0001";
        ElementType = 5; NoSinglePointOfFailure = false;
        NoSinglePointOfFailureDefault = false;
        DataRedundancyMax = 1; DataRedundancyMin = 1; DataRedundancyDefault = 1;
        PackageRedundancyMax = 1; PackageRedundancyMin = 1; PackageRedundancyDefault = 1;
        ParityLayoutDefault = 3; Caption = "SPSC:Pool1";
        ElementName = "Capabilities for storage pool on CF2A5091300089 storage system"; };
     instance of CIM_StorageCapabilities as $StPC3 {
        InstanceID = "ACME+CF2A5091300089+Primordial";
        ElementType = 5; NoSinglePointOfFailure = false;
        NoSinglePointOfFailureDefault = false;
        DataRedundancyMax = 1; DataRedundancyMin = 1; DataRedundancyDefault = 1;
        PackageRedundancyMax = 1; PackageRedundancyMin = 1; PackageRedundancyDefault = 1;
        ParityLayoutDefault = 2; Caption = "SPSC:PSP1";
        ElementName = "Capabilities for storage pool on CF2A5091300089 storage system"; };

    // A CIM_ElementCapabilities (StorageCapabilities to StoragePool) instance
     instance of CIM_ElementCapabilities as $ECCSP0 {
        Capabilities = $StPC0;
        ManagedElement = $CSP0; };
     instance of CIM_ElementCapabilities as $ECCSP1 {
        Capabilities = $StPC1;
        ManagedElement = $CSP1; };
     instance of CIM_ElementCapabilities as $ECPSP0 {
        Capabilities = $StPC3;
        ManagedElement = $PSP0; };

    // A CIM_LogicalDisk instance
     instance of CIM_LogicalDisk as $SV5 {
        InstanceID = "SV5";
        Name = "LD00005"; NameFormat = 1;
        Usage = 2; 
        BlockSize = 512; NumberOfBlocks = 40960; ConsumableBlocks = 40960;
        IsBasedOnUnderlyingRedundancy = true; ExtentStatus = {17};
        NoSinglePointOfFailure = false; DataRedundancy = 0; PackageRedundancy = 0;
        DeltaReservation = 0; Primordial = false;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089"; CreationClassName = "CIM_LogicalDisk";
        DeviceID = "00005";
        OperationalStatus = {2};
        Caption = "LD"; ElementName = "LD 5"; };
        
     instance of CIM_LogicalDisk as $SV6 {
        InstanceID = "SV6";
        Name = "LD00006"; NameFormat = 1;
        Usage = 2; 
        BlockSize = 512; NumberOfBlocks = 40960; ConsumableBlocks = 40960;
        IsBasedOnUnderlyingRedundancy = true; ExtentStatus = {17};
        NoSinglePointOfFailure = false; DataRedundancy = 0; PackageRedundancy = 0;
        DeltaReservation = 0; Primordial = false;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089"; CreationClassName = "CIM_LogicalDisk";
        DeviceID = "00006";
        OperationalStatus = {2};
        Caption = "LD"; ElementName = "LD 6"; };
        
     instance of CIM_LogicalDisk as $SV7 {
        InstanceID = "SV7";
        Name = "LD00007"; NameFormat = 1;
        Usage = 2; 
        BlockSize = 512; NumberOfBlocks = 40960; ConsumableBlocks = 40960;
        IsBasedOnUnderlyingRedundancy = true; ExtentStatus = {17};
        NoSinglePointOfFailure = false; DataRedundancy = 0; PackageRedundancy = 0;
        DeltaReservation = 0; Primordial = false;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089"; CreationClassName = "CIM_LogicalDisk";
        DeviceID = "00007";
        OperationalStatus = {2};
        Caption = "LD"; ElementName = "LD 7"; };
        
    // A CIM_StorageSetting instance
     instance of CIM_StorageSetting as $SVS5 {
       InstanceID = "ACME+CF2A5091300089+00005"; NoSinglePointOfFailure = false;
       DataRedundancyMax = 1; DataRedundancyMin = 1; DataRedundancyGoal = 1;
       PackageRedundancyMax = 0; PackageRedundancyMin = 0; PackageRedundancyGoal = 0;
       ChangeableType = 0;
       ExtentStripeLength = 0; ExtentStripeLengthMin = 0; ExtentStripeLengthMax = 0;
       ParityLayout = 1; UserDataStripeDepth = 0; UserDataStripeDepthMin = 0;
       UserDataStripeDepthMax = 0; StorageExtentInitialUsage = 1;
       StoragePoolInitialUsage = 1; Caption = "LDSS:00005";
       ElementName = "RAID0"; };
       
     instance of CIM_StorageSetting as $SVS6 {
       InstanceID = "ACME+CF2A5091300089+00006"; NoSinglePointOfFailure = false;
       DataRedundancyMax = 1; DataRedundancyMin = 1; DataRedundancyGoal = 1;
       PackageRedundancyMax = 0; PackageRedundancyMin = 0; PackageRedundancyGoal = 0;
       ChangeableType = 0;
       ExtentStripeLength = 0; ExtentStripeLengthMin = 0; ExtentStripeLengthMax = 0;
       ParityLayout = 1; UserDataStripeDepth = 0; UserDataStripeDepthMin = 0;
       UserDataStripeDepthMax = 0; StorageExtentInitialUsage = 1;
       StoragePoolInitialUsage = 1; Caption = "LDSS:00006";
       ElementName = "RAID0"; };
       
     instance of CIM_StorageSetting as $SVS7 {
       InstanceID = "ACME+CF2A5091300089+00007"; NoSinglePointOfFailure = false;
       DataRedundancyMax = 1; DataRedundancyMin = 1; DataRedundancyGoal = 1;
       PackageRedundancyMax = 0; PackageRedundancyMin = 0; PackageRedundancyGoal = 0;
       ChangeableType = 0;
       ExtentStripeLength = 0; ExtentStripeLengthMin = 0; ExtentStripeLengthMax = 0;
       ParityLayout = 1; UserDataStripeDepth = 0; UserDataStripeDepthMin = 0;
       UserDataStripeDepthMax = 0; StorageExtentInitialUsage = 1;
       StoragePoolInitialUsage = 1; Caption = "LDSS:00007";
       ElementName = "RAID0"; };

    // A CIM_ElementSettingData instance
      instance of CIM_ElementSettingData as $ESDSV5 {
        IsDefault = 2; IsCurrent = 1; 
        ManagedElement = $SV5;
        SettingData = $SVS5; };
      instance of CIM_ElementSettingData as $ESDSV6 {
        IsDefault = 2; IsCurrent = 1; 
        ManagedElement = $SV6;
        SettingData = $SVS6; };
      instance of CIM_ElementSettingData as $ESDSV7 {
        IsDefault = 2; IsCurrent = 1; 
        ManagedElement = $SV7;
        SettingData = $SVS7; };

    // CIM_AllocatedFromStoragePool instances
     instance of CIM_AllocatedFromStoragePool as $SVAFSP5 {
        SpaceConsumed = 20480; SpaceLimit = 0;
        SpaceLimitWarningThreshold = 0;
        Antecedent = $CSP0;
        Dependent = $SV5; };

     instance of CIM_AllocatedFromStoragePool as $SVAFSP6 {
        SpaceConsumed = 20480; SpaceLimit = 0;
        SpaceLimitWarningThreshold = 0;
        Antecedent = $CSP0;
        Dependent = $SV6; };
     instance of CIM_AllocatedFromStoragePool as $SVAFSP7 {
        SpaceConsumed = 20480; SpaceLimit = 0;
        SpaceLimitWarningThreshold = 0;
        Antecedent = $CSP0;
        Dependent = $SV7; };

    // A CIM_SystemDevice instance
     instance of CIM_SystemDevice as $SDSV05 {
        GroupComponent = $CS0;
        PartComponent = $SV5; };
     instance of CIM_SystemDevice as $SDSV06 {
        GroupComponent = $CS0;
        PartComponent = $SV6; };
     instance of CIM_SystemDevice as $SDSV07 {
        GroupComponent = $CS0;
        PartComponent = $SV7; };

    // NAS Network Ports Profile
    // CIM_NetworkPort
     instance of CIM_NetworkPort as $NPP0 { InstanceID = "NPP0";
        PermanentAddress = "50060162446406C5";
        NetworkAddresses = {}; 
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A"; CreationClassName = "CIM_NetworkPort";
        DeviceID = "ACME+CF2A5091300089+SP_A+0"; 
        OperationalStatus = {2};
        Caption = "NP:SP_A:0";
        ElementName = "Port SP_A:0"; };

     instance of CIM_NetworkPort as $NPP1 { InstanceID = "NP1";
        PermanentAddress = "50060163446406C5"; NetworkAddresses = {};
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_B"; CreationClassName = "CIM_NetworkPort";
        DeviceID = "ACME+CF2A5091300089+SP_B+1"; 
        OperationalStatus = {2};
        Caption = "NP:SP_B:1";
        ElementName = "Port SP_B:1"; };
////////////////////////////////////////// (was $SPE0)
// CIM_ProtocolEndpoint
     instance of CIM_ProtocolEndpoint as $CIFSPE0 { InstanceID = "CIFSPE0";
        Name = "50060160446006C5+CIFS0";
        NameFormat = "<PortAddress>+<Protocol><Number>";
        OperationalStatus = {2}; ProtocolIFType = 4201;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A+CIFS0"; CreationClassName = "CIM_ProtocolEndpoint";
        Description = "CIFS ProtocolEndPoint";
        Caption = "CIFSPE:CIFS://SP_A:CIFS";
        ElementName = "ACME CIFS Protocol Endpoint"; };
     instance of CIM_ProtocolEndpoint as $NFSPE0 { InstanceID = "NFSPE0";
        Name = "50060160446006C5+NFS0";
        NameFormat = "<PortAddress>+<Protocol><Number>";
        OperationalStatus = {2}; ProtocolIFType = 4200;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A+NFS0"; CreationClassName = "CIM_ProtocolEndpoint";
        Description = "NFS ProtocolEndPoint";
        Caption = "NFSPE:CIFS://SP_A:NFS";
        ElementName = "ACME NFS Protocol Endpoint"; };
// CIM_IPProtocolEndpoint
     instance of CIM_IPProtocolEndpoint as $IPPEN { InstanceID = "IPPEN";
        Description = "IP ProtocolEndPoint";
        Name = "50060160446006C5+IP0"; 
        NameFormat = "<PortAddress>+<Protocol><Number>";
        OperationalStatus = {2}; ProtocolIFType = 4096;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A+NFS0"; 
        CreationClassName = "CIM_IPProtocolEndpoint"; };
     instance of CIM_IPProtocolEndpoint as $IPPEC { InstanceID = "IPPEC";
        Description = "IP ProtocolEndPoint";
        Name = "50060160446006C5+IP1"; 
        NameFormat = "<PortAddress>+<Protocol><Number>";
        OperationalStatus = {2}; ProtocolIFType = 4096;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A+CIFS0"; 
        CreationClassName = "CIM_IPProtocolEndpoint"; };
// CIM_TCPProtocolEndpoint
     instance of CIM_TCPProtocolEndpoint as $TCPPEN { InstanceID = "TCPPEN";
        Description = "TCP ProtocolEndPoint";
        Name = "50060160446006C5+TCP0"; 
        NameFormat = "<PortAddress>+<Protocol><Number>";
        OperationalStatus = {2}; ProtocolIFType = 4111;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A+NFS0"; 
        CreationClassName = "CIM_TCPProtocolEndpoint"; };
     instance of CIM_TCPProtocolEndpoint as $TCPPEC { InstanceID = "TCPPEC";
        Description = "TCP ProtocolEndPoint";
        Name = "50060160446006C5+TCP1"; 
        NameFormat = "<PortAddress>+<Protocol><Number>";
        OperationalStatus = {2}; ProtocolIFType = 4111;
        SystemCreationClassName = "CIM_ComputerSystem";
        SystemName = "ACME+CF2A5091300089+SP_A+CIFS0"; 
        CreationClassName = "CIM_TCPProtocolEndpoint"; };
       
    // A CIM_DeviceSAPImplementation instance
     instance of CIM_DeviceSAPImplementation as $NPDSICIFS {
        Antecedent = $NPP0; 
        Dependent = $CIFSPE0; };
     instance of CiM_DeviceSAPImplementation AS $NPDSINFS {
        Antecedent = $NPP0;
        Dependent = $NFSPE0; };
     instance of CIM_DeviceSAPImplementation as $NPDSINIP {
        Antecedent = $NPP0; 
        Dependent = $IPPEN; };
     instance of CiM_DeviceSAPImplementation AS $NPDSICIP {
        Antecedent = $NPP0;
        Dependent = $IPPEC; };

    // A CIM_HostedAccessPoint instance
     instance of CIM_HostedAccessPoint as $HAPCIFSS_CIFSPE {
        Antecedent = $CS_CIFS0;
        Dependent = $CIFSPE0; };
     instance of CIM_HostedAccessPoint as $HAPCIFSS_IPPE {
        Antecedent = $CS_CIFS0;
        Dependent = $IPPEC; };
     instance of CIM_HostedAccessPoint as $HAPCIFSS_TCPPE {
        Antecedent = $CS_CIFS0;
        Dependent = $TCPPEC; };
     instance of CIM_HostedAccessPoint as $HAPNFSS_NFSPE {
        Antecedent = $CS_NFS0;
        Dependent = $NFSPE0; };
     instance of CIM_HostedAccessPoint as $HAPNFSS_IPPE {
        Antecedent = $CS_NFS0;
        Dependent = $IPPEN; };
     instance of CIM_HostedAccessPoint as $HAPNFSS_TCPPE {
        Antecedent = $CS_NFS0;
        Dependent = $TCPPEN; };

    // A CIM_SystemDevice (Port) instance
     instance of CIM_SystemDevice as $SDNNP00 {
        GroupComponent = $CS_A;
        PartComponent = $NPP0; };
     instance of CIM_SystemDevice as $SDNNP01 {
        GroupComponent = $CS_A;
        PartComponent = $NPP1; };

// NAS HEAD ITEMS

   // CIM_StorageExtent Instances
    instance of CIM_StorageExtent as $PRIMESE00 {
      BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
      ExtentStatus = {16};
      Primordial = true;
      Name = "0_0_0"; NameFormat = 1;
      SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
      CreationClassName = "CIM_StorageExtent";
      DeviceID = "ACME+CF2A5091300089+2;3;;0_0_0;;;0;0;;";
      OperationalStatus = {2};
      ExtentDiscriminator = {"SNIA:Imported"};
      ElementName = "Primordial 0_0_0"; };
      
    instance of CIM_StorageExtent as $PRIMESE01 {
      BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
      ExtentStatus = {16};
      Primordial = true;
      Name = "0_0_1"; NameFormat = 1;
      SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
      CreationClassName = "CIM_StorageExtent";
      DeviceID = "ACME+CF2A5091300089+2;3;;0_0_1;;;0;0;;";
      OperationalStatus = {2};
      ExtentDiscriminator = {"SNIA:Imported"};
      ElementName = "Primordial 0_0_1"; };
      
    instance of CIM_StorageExtent as $PRIMESE02 {
       BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
       ExtentStatus = {16};
       Primordial = true;
       Name = "0_0_2"; NameFormat = 1;
       SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
       CreationClassName = "CIM_StorageExtent";
       DeviceID = "ACME+CF2A5091300089+2;3;;0_0_2;;;0;0;;";
       OperationalStatus = {2};
       ExtentDiscriminator = {"SNIA:Imported"};
       ElementName = "Primordial 0_0_2"; };
       
    instance of CIM_StorageExtent as $PRIMESE03 {
       BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
       ExtentStatus = {16};
       Primordial = true;
       Name = "0_0_3"; NameFormat = 1;
       SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
       CreationClassName = "CIM_StorageExtent";
       DeviceID = "ACME+CF2A5091300089+2;3;;0_0_3;;;0;0;;";
       OperationalStatus = {2};
       ExtentDiscriminator = {"SNIA:Imported"};
       ElementName = "Primordial 0_0_3"; };
       
    instance of CIM_StorageExtent as $PRIMESE04 {
       BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
       ExtentStatus = {16};
       Primordial = true;
       Name = "0_0_4"; NameFormat = 1;
       SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
       CreationClassName = "CIM_StorageExtent";
       DeviceID = "ACME+CF2A5091300089+2;3;;0_0_4;;;0;0;;";
       OperationalStatus = {2};
       ExtentDiscriminator = {"SNIA:Imported"};
       ElementName = "Primordial 0_0_4"; };
       
    instance of CIM_StorageExtent as $PRIMESE05 {
       BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
       ExtentStatus = {16};
       Primordial = true;
       Name = "0_0_5"; NameFormat = 1;
       SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
       CreationClassName = "CIM_StorageExtent";
       DeviceID = "ACME+CF2A5091300089+2;3;;0_0_5;;;0;0;;";
       OperationalStatus = {2};
       ExtentDiscriminator = {"SNIA:Imported"};
       ElementName = "Primordial 0_0_5"; };
       
    instance of CIM_StorageExtent as $PRIMESE06 {
       BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
       ExtentStatus = {16};
       Primordial = true;
       Name = "0_0_6"; NameFormat = 1;
       SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
       CreationClassName = "CIM_StorageExtent";
       DeviceID = "ACME+CF2A5091300089+2;3;;0_0_6;;;0;0;;";
       OperationalStatus = {2};
       ExtentDiscriminator = {"SNIA:Imported"};
       ElementName = "Primordial 0_0_6"; };
       
    instance of CIM_StorageExtent as $PRIMESE07 {
       BlockSize = 512; NumberOfBlocks = 562882560; ConsumableBlocks = 562882560;
       ExtentStatus = {16};
       Primordial = true;
       Name = "0_0_7"; NameFormat = 1;
       SystemCreationClassName = "CIM_ComputerSystem"; SystemName = "ACME+CF2A5091300089";
       CreationClassName = "CIM_StorageExtent";
       DeviceID = "ACME+CF2A5091300089+2;3;;0_0_7;;;0;0;;";
       OperationalStatus = {2};
       ExtentDiscriminator = {"SNIA:Imported"};
       ElementName = "Primordial 0_0_7"; };

   // CIM_AssociatedComponentExtent Instances
    instance of CIM_AssociatedComponentExtent as $ACEPSE00 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE00; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE01 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE01; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE02 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE02; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE03 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE03; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE04 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE04; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE05 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE05; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE06 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE06; };
      
    instance of CIM_AssociatedComponentExtent as $ACEPSE07 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE07; };
 
   // CIM_ConcreteComponent Instances
    instance of CIM_ConcreteComponent as $CC00 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE00; };
      
    instance of CIM_ConcreteComponent as $CC01 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE01; };
      
    instance of CIM_ConcreteComponent as $CC02 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE02; };
      
    instance of CIM_ConcreteComponent as $CC03 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE03; };
      
    instance of CIM_ConcreteComponent as $CC04 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE04; };
      
    instance of CIM_ConcreteComponent as $CC05 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE05; };
      
    instance of CIM_ConcreteComponent as $CC06 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE06; };
      
    instance of CIM_ConcreteComponent as $CC07 {
      GroupComponent = $PSP0;
      PartComponent = $PRIMESE07; };

    // CIM_SystemDevice Instances (Needed for StorageExtents)
    instance of CIM_SystemDevice as $SDPSE00 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE00; };
      
    instance of CIM_SystemDevice as $SDPSE01 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE01; };
      
    instance of CIM_SystemDevice as $SDPSE02 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE02; };
      
    instance of CIM_SystemDevice as $SDPSE03 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE03; };
      
    instance of CIM_SystemDevice as $SDPSE04 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE04; };
      
    instance of CIM_SystemDevice as $SDPSE05 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE05; };
      
    instance of CIM_SystemDevice as $SDPSE06 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE06; };
      
    instance of CIM_SystemDevice as $SDPSE07 {
      GroupComponent = $CS0;
      PartComponent = $PRIMESE07; };

    // Software Profile
    // CIM_InstalledSoftwareIdentity
       instance of CIM_InstalledSoftwareIdentity as $ISIArray {
          InstalledSoftware = $NASHeadSoftware;
          System = $CS0; };
          
       instance of CIM_InstalledSoftwareIdentity as $ISIServer {
          InstalledSoftware = $ServerSoftware;
          System = $ServerSystem; };
          
//       instance of CIM_InstalledSoftwareIdentity as $ISIWBEMServer {
//          InstalledSoftware = $WBEMServerSoftware;
//          System = $ServerSystem; };

////////////////////////////////////////// 
// Filesystem Profile instances go here
// CIM_LocalFileSystem instances
     instance of CIM_LocalFileSystem as $LFS11 {
       AvailableSpace = 18874368;
       BlockSize = 1024;
       CSCreationClassName = "CIM_ComputerSystem";
       CSName = "ACME+CF2A5091300089";
       CasePreserved = true;
       CaseSensitive = true;
       CreationClassName = "CIM_LocalFileSystem";
       FileSystemSize = 19922944;
       FileSystemType = "ACME_FS";
       MaxFileNameLength = 255;
       Name = "11";
       NumberOfFiles = 0;
       OperationalStatus = {2};
       Caption = "FS:fs11";
       ElementName = "fs11"; };
     instance of CIM_LocalFileSystem as $LFS14 {
       AvailableSpace = 16777216;
       BlockSize = 1024;
       CSCreationClassName = "CIM_ComputerSystem";
       CSName = "ACME+CF2A5091300089";
       CasePreserved = true;
       CaseSensitive = true;
       CreationClassName = "CIM_LocalFileSystem";
       FileSystemSize = 19922944;
       FileSystemType = "ACME_FS";
       MaxFileNameLength = 255;
       Name = "14";
       NumberOfFiles = 0;
       OperationalStatus = {2};
       Caption = "FS:fs14";
       ElementName = "fs14"; };
  // SHRUB: CIM_HostedFileSystem to ComputerSystem
     instance of CIM_HostedFileSystem as $HFSLFSCS11 {
       GroupComponent = $CS0;
       PartComponent = $LFS11; };
     instance of CIM_HostedFileSystem as $HFSLFSCS14 {
       GroupComponent = $CS0;
       PartComponent = $LFS14; };
//   CIM_ResidesOnExtent to LogicalDisk
     instance of CIM_ResidesOnExtent as $ROELFSLD11 {
       Antecedent = $SV5;
       Dependent = $LFS11; };
     instance of CIM_ResidesOnExtent as $ROELFSLD14 {
       Antecedent = $SV7;
       Dependent = $LFS14; };
//   CIM_SharedElement to FileShare (see below)
//   CIM_ElementSettingData to CIM_FileSystemSetting (see below)
     

// File Storage Instances go here (See above)

// File Export Instances go here
     instance of CIM_CIFSShare as $CIFS14 {
       SharingDirectory = true;
       InstanceID = "ACME+CF2A5091300089+SP_A+CIFS0:14";
       Name = "CIFS 14";
       OperationalStatus = {2};
       Caption = "CIFSFS:14";
       ElementName = "CIFS 14"; };
     instance of CIM_NFSShare as $NFS11 {
       SharingDirectory = true;
       InstanceID = "ACME+CF2A5091300089+SP_A+NFS0:11";
       Name = "NFS 11";
       OperationalStatus = {2};
       Caption = "NFS 11";
       ElementName = "NFS 11"; };
  // SHRUB: CIM_HostedShare to CIM_ComputerSystem
     instance of CIM_HostedShare as $HShCS14 {
       Antecedent = $CS_CIFS0;
       Dependent = $CIFS14; };
     instance of CIM_HostedShare as $HShCS11 {
       Antecedent = $CS_NFS0;
       Dependent = $NFS11; };
//   CIM_FileShareSettingData to CIM_ExportedFileShareSetting (see below)
//   CIM_SAPAvailableForFileShare to CIM_ProtocolEndpoint
     instance of CIM_SAPAvailableForFileShare as $SAFFSFShPE14 {
       ManagedElement = $CIFS14;
       AvailableSAP = $CIFSPE0; };
     instance of CIM_SAPAvailableForFileShare as $SAFFSFShPE11 {
       ManagedElement = $NFS11;
       AvailableSAP = $NFSPE0; };
//   CIM_SharedElement to CIM_LocalFileSystem
     instance of CIM_SharedElement as $SEFShLFS14 {
       SameElement = $CIFS14;
       SystemElement = $LFS14; };
     instance of CIM_SharedElement as $SEFShLFS11 {
       SameElement = $NFS11;
       SystemElement = $LFS11; };
     
     instance of CIM_ExportedFileShareSetting as $EFShS14 {
       AccessPoints = 5;
       DefaultReadWrite = 3;
       DefaultUserIdSupported = 2;
       FileSharingProtocol = 3;
       InitialEnabledState = 2;
       ProtocolVersions = {"SMB3.0"};
       RootAccess = 3;
       ElementName = "CIFS 14 Setting";
       InstanceID = "ACME+CF2A5091300089+SP_A+CIFS0:14";
       Caption = "CIFS 14 Setting"; };
     instance of CIM_ExportedFileShareSetting as $EFShS11 {
       AccessPoints = 4;
       DefaultReadWrite = 3;
       DefaultUserIdSupported = 2;
       FileSharingProtocol = 2;
       InitialEnabledState = 2;
       ProtocolVersions = {"v2", "v3", "v4"};
       RootAccess = 3;
       ElementName = "NFS 11 Setting";
       InstanceID = "ACME+CF2A5091300089+SP_A+NFS0:11";
       Caption = "NFS 11 Setting"; };
  // SHRUB: CIM_FileShareSettingData to CIM_FileShare
     instance of CIM_FileShareSettingData as $FSSDEFSSFSh11 {
       ManagedElement = $NFS11;
       SettingData = $EFShS11; };
     instance of CIM_FileShareSettingData as $FSSDEFSSFSh14 {
       ManagedElement = $CIFS14;
       SettingData = $EFShS14; };

// FSPerf instances go here
